config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import gallery.api_views, gallery.views

urlpatterns = [
    path('', gallery.views.home, name='home'),
    path('gallery/', include('gallery.urls')),
    path('admin/', admin.site.urls),
    
    path('api/v1/albums', gallery.api_views.AlbumList.as_view()),
    path('api/v1/albums/new', gallery.api_views.AlbumCreate.as_view()),
    path('api/v1/albums/<int:id>/', gallery.api_views.AlbumRetrieveUpdateDestroy.as_view()),

    path('api/v1/photographs', gallery.api_views.PhotographList.as_view()),
    path('api/v1/photographs/new', gallery.api_views.PhotographCreate.as_view()),
    path('api/v1/photographs/<int:id>/', gallery.api_views.PhotographRetrieveUpdateDestroy.as_view()),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'gallery'
urlpatterns = [
    # '/gallery/
    path('', views.IndexView.as_view(), name='index'),
    # '/gallery/1/
    path('<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'),
    # '/gallery/1/1/'
    path('<int:album_id>/<int:pk>/', views.PhotoDetailView.as_view(), name='photo_detail'),
    # path('<int:album_id>/<int:photo_id>/', views.photo_detail, name='photo_detail'),
    # '/gallery/about
    path('about', views.about, name='about'),

]

gallery/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=1024)
    thumbnail = models.ImageField(upload_to='photos/', default = 'photos/no-image.png')
    
    def __str__(self):
        return self.title

class Photograph(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1024)
    photo = models.ImageField(upload_to='photos/', default = 'photos/no-image.png')
    creation_date = models.DateField('date created')

    def __str__(self):
        return self.name

gallery/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.db.models import Q
from django.views import generic
# Create your views here.

from .models import Album,Photograph

# def index(request):
#     album_list = Album.objects.order_by('-title')
#     return render(request, 'gallery/index.html', {'album_list': album_list})
class IndexView(generic.ListView):
    template_name = 'gallery/index.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        return Album.objects.order_by('title')

# def album_detail(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     photo_list = album.photograph_set.all()
#     return render(request, 'gallery/album_detail.html', 
#     {
#         'album': album,
#         'photo_list': photo_list,
#     })
class AlbumDetailView(generic.DetailView):
    model = Album
    context_object_name = 'album'
    template_name = 'gallery/album_detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        self.album = get_object_or_404(Album, id=self.kwargs['pk'])
        context['photo_list'] = self.album.photograph_set.all()
        return context


class PhotoDetailView(generic.DetailView):
    model = Photograph
    context_object_name = 'start_photo'
    template_name = 'gallery/photo_detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        self.album = get_object_or_404(Album, id=self.kwargs['album_id'])
        context['album'] = self.album
        context['photo_list'] = self.album.photograph_set.exclude(pk=self.kwargs['pk'])
        context['prev_photos'] = self.album.photograph_set.filter(pk__lt=self.kwargs['pk'])
        context['next_photos'] = self.album.photograph_set.filter(pk__gt=self.kwargs['pk'])
        return context

def about(request):
    return render(request, 'gallery/about.html')

def home(request):
    return render(request, 'gallery/home.html')

gallery/templates/gallery/about.html
{% extends 'gallery/base.html' %}


{% block content %}

<nav   aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'gallery:index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">About</li>
  </ol>
</nav>
<header>
  <h1>About</h1>
</header>
<br>
<p>I'm a photographer based in Miami, Florida. </p> 
<p>I photograph events and artists in the local Miami music and arts scene.</p>

{% endblock %}         

gallery/templates/gallery/album_detail.html
{% extends 'gallery/base.html' %}
{% load thumbnail %}
<!-- ALBUM IMAGES -->
{% block content %}
    <nav   aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'gallery:index' %}">Albums</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ album.title }}</li>
      </ol>
    </nav>
    <header>
      <h1>{{album.title}}</h1>
    </header>
    {% if photo_list %}
      <ul class="images-container">
        {% for photograph in album.photograph_set.all %}
        <li class="thumbnail">
          <a href="{% url 'gallery:photo_detail' album.id photograph.id %}">
            <div class="image-detail">
              <h4>{{ photograph.name }}</h4>
              <p>Description: {{ photograph.description }}</p>
              <p>Taken: {{ photograph.creation_date }}</p>
            </div>
            <!-- <img class="image" src="{{photograph.photo.url}}" alt="Album Image" /> -->
            <img 
                class="image" 
                src="{% thumbnail photograph.photo '1920' as im %}{{ im.url }}{% endthumbnail %}"
                srcset="{% thumbnail photograph.photo '544' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photograph.photo '768' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photograph.photo '992' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photograph.photo '1200' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photograph.photo '1920' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                alt="Album Image"
                sizes="100vw"  
            />
          </a>
        </li>
        <br>
        {% endfor %}
        <li></li>
      </ul>
    {% else %}
      <p>No photos are available.</p>
    {% endif %}
{% endblock %}  

gallery/templates/gallery/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>irie.io images</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="This site displays the photogpraphy work of Irene Polo"
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'gallery/style.css' %}">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" rel="stylesheet">
    <!-- Social Link Icons -->
    <script src="https://kit.fontawesome.com/f25d61f966.js" crossorigin="anonymous"></script> 
  </head>
  <body>
   
    <div class="root">

      <!-- NAVBAR -->
      <nav class="navbar flex-column-item">
          <a class="navbar-brand nav-item" href="{% url 'home' %}">
            irie.io images
          </a>
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'gallery:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Buy Prints</a>
            </li>
          </ul>
      </nav>
      
      <!-- CONTENT -->
      <section class="flex-column-item block-content">
        {% block content %}
        {% endblock %}
      </section>

      <!-- FOOTER -->
      <footer class="flex-column-item">
          <!-- GENERAL -->
          <div class="ft-item ft-info">
            <a href="{% url 'gallery:index' %}">irie.io images</a>
            <a href="mailto:ipolo1969@gmail.com" id="email">ipolo1969@gmail.com</a>
          </div>
          <!-- SOCIAL BUTTONS -->
          <div class="ft-item ft-social">
            <ul class="ft-social-list">
              <li><a href="https://www.instagram.com/irie.io.images/"><i class="fab fa-instagram"></i></a></li>
              <li><a href="#"><i class="fab fa-github"></i></a></li>
              <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
      </footer>

    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

gallery/templates/gallery/home.html
<!DOCTYPE html>
<html class="homepage">
  <head>
    <meta charset="utf-8">
    <title>irie.io images</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="This site displays the photogpraphy work of Irene Polo"
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'gallery/style.css' %}">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400&display=swap" rel="stylesheet">
    <!-- Social Link Icons -->
    <script src="https://kit.fontawesome.com/f25d61f966.js" crossorigin="anonymous"></script> 
  </head>
  <body class="homepage">

    <div class="home-background">
        <h1>Irene Polo</h1>
        <div class="homepage-details">
            <p>Photographer based in Miami</p>
            <p></p>
            <a href="{% url 'gallery:index'%}" class="btn btn-outline-light">Portfolio</a>
        </div>
        <!-- <img class="image home-background" src="{% static 'gallery/images/home_image.jpg' %}" alt="Album Image" /> -->
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

gallery/templates/gallery/index.html
{% extends 'gallery/base.html' %}
{% load thumbnail %}
<!-- ALBUMS -->
{% block content %}
  <header class="block-content-item">
    <h1>Albums</h1>
  </header>
  {% if album_list %}
    <ul class="block-content-item images-container">
    {% for album in album_list %}
      <li class="thumbnail">
        <a href="{% url 'gallery:album_detail' album.id %}">
            <div class="image-detail">
              <h4>{{ album.title }}</h4>
              <!-- <h6>{{ album.description }}</h6> -->
            </div>
            <!-- <img class="image" src="{{album.thumbnail.url}}" alt="Album Thumbnail"  /> -->
            <img 
                class="image" 
                src="{% thumbnail album.thumbnail '1920' as im %}{{ im.url }}{% endthumbnail %}"
                srcset="{% thumbnail album.thumbnail '544' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail album.thumbnail '768' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail album.thumbnail '992' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail album.thumbnail '1200' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail album.thumbnail '1920' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                alt="Album Thumbnail"
                sizes="100vw"  
            />
            
        </a>
      </li>
        <!-- <br> -->
    {% endfor %}
    <!--Note: add more <li></li> if -->
    <li></li>

    </ul>
  {% else %}
      <p>No albums are available.</p>
  {% endif %}
 
{% endblock %}

gallery/templates/gallery/photo_detail.html
{% extends 'gallery/base.html' %}
{% load thumbnail %}

{% block content %}
<nav   aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'gallery:index' %}">Albums</a></li>
      <li class="breadcrumb-item"><a href="{% url 'gallery:album_detail' album.id%}">{{ album.title }}</a></li>
      <li class="breadcrumb-item active" aria-current="page"></li>
    </ol>
</nav>

<!-- Carousel -->
<div id="carouselExampleControls" class="carousel slide" data-interval="false" data-ride="carousel">
    <div class="carousel-inner">
        {% for photo in prev_photos %}
        <div class="carousel-item">
            <img 
                class="d-block w-100" 
                src="{% thumbnail photo.photo '1920' as im %}{{ im.url }}{% endthumbnail %}"
                srcset="{% thumbnail photo.photo '544' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photo.photo '768' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photo.photo '992' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photo.photo '1200' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photo.photo '1920' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                alt="{{photo.name}}"
                sizes="100vw"  
            />
            <div class="carousel-caption d-none d-md-block">
                <h5>{{photo.name}}</h5>
                <p>{{photo.description}}</p>
                <p>{{photo.creation_date}}</p>
            </div>
        </div>
        {% endfor %}

        <div class="carousel-item active">
            <img 
                class="d-block w-100" 
                src="{% thumbnail start_photo.photo '1920' as im %}{{ im.url }}{% endthumbnail %}"
                srcset="{% thumbnail start_photo.photo '544' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail start_photo.photo '768' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail start_photo.photo '992' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail start_photo.photo '1200' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail start_photo.photo '1920' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                alt="{{start_photo.name}}"
                sizes="100vw"  
            />
            <div class="carousel-caption d-none d-md-block">
                <h5>{{start_photo.name}}</h5>
                <p>{{start_photo.description}}</p>
                <p>{{start_photo.creation_date}}</p>
            </div>
        </div>

        {% for photo in next_photos %}
        <div class="carousel-item">
            <img 
                class="d-block w-100" 
                src="{% thumbnail photo.photo '1920' as im %}{{ im.url }}{% endthumbnail %}"
                srcset="{% thumbnail photo.photo '544' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photo.photo '768' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photo.photo '992' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photo.photo '1200' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %},
                        {% thumbnail photo.photo '1920' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                alt="{{photo.name}}"
                sizes="100vw"  
            />
            <div class="carousel-caption d-none d-md-block">
                <h5>{{photo.name}}</h5>
                <p>{{photo.description}}</p>
                <p>{{photo.creation_date}}</p>
            </div>
        </div>
        {% endfor %}
    </div>

    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
    

<!--Thumbnails-->
<!-- <section class="images-container">
    {% for photo in photo_list %}
    <div class="thumbnail">
        <img class="image" src="/media/{{photo.photo}}" alt="Album Image" />
    </div>                
    {% endfor %}
</section> -->
        
{% endblock %}     